services:
  source_db:
    image: postgres:latest
    hostname: source_db
    container_name: source_startup_container
    restart: on-failure
    environment:
      - POSTGRES_DB=startup_investments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cobapassword
    volumes:
      - ./source_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432 
    networks:
      - my_network

  pipeline_db:
    image: postgres:latest
    hostname: pipeline_db
    container_name: target_db_container
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cobapassword
    volumes:
      - ./target_db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./target_db/etl_log.sql:/docker-entrypoint-initdb.d/02-etl_log.sql
      - ./target_db/staging.sql:/docker-entrypoint-initdb.d/03-staging.sql
      - ./target_db/warehouse.sql:/docker-entrypoint-initdb.d/04-dwh.sql
    ports:
      - 5435:5432 
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge